### ISSUE TITLE
Get "Testing.au3" back to work

### ISSUE THREAD

**Issue by sven-seyfert** [TheDcoder/Scheduler.au3#4]
Hi @TheDcoder ,

you mentioned already:

> You got the idea, leave Testing.au3 from this commit so that we can deal with it later in another commit. I understand that this can cause a bit of confusion as your new script is called Tests.au3 but it's just temporary so let's leave it until we have a proper example script. Deleting it entirely is also on the table, but I haven't thought much about it yet.

How about I refactore the `Testing.au3` script at least in this way, that it works properly again? Otherwise this

``` autoit
While True
	Local $sInput = InputBox("Timesheet Multi Test", "Enter timings")
	If @error Then ExitLoop
	Local $aSchedule = StringSplit($sInput, ',', 2)
	For $i = 0 To UBound($aSchedule) - 1
		If StringLeft($aSchedule[$i], 1) <> '[' Then ContinueLoop
		$aSchedule[$i] = StringMid($aSchedule[$i], 2, StringLen($aSchedule[$i]) - 2)
		$aSchedule[$i] = StringSplit($aSchedule[$i], ';', 2)
	Next
	Local $aSheet = _Scheduler_MakeTimesheet($aSchedule)
	_ArrayDisplay($aSheet, "Timesheet Multi Test")
WEnd
```

breaks all the time a user tries this. I understand that you would like to have a proper example, but at least one example that works 😅 . The second step could be to rename the file (this would avoid the possible confusion).

**Should I do it or is it not worthy enough?**

Best regards
Sven

**Comment by TheDcoder** [comment]
Why not start fresh and make a similar script which is a bit cleaner? It could serve as a basic example. Better than doing any work on this in my opinion :)

**Comment by sven-seyfert** [comment]
You're right. Not today, but maybe coming soon 😀 .
